name: Update data

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: AWS CLI
      uses: chrislennon/action-aws-cli@1.1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.5 
        args: install
    - name: Fetch
      uses: abatilo/actions-poetry@v1.5.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      with:
        python_version: 3.8.0
        poetry_version: 1.0.5 
        args: run ./update.sh
