name: Update data

on:
  push:
    branches:
    - master
  schedule:
  - cron: '0 */8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python_version: 3.8
    - uses: chrislennon/action-aws-cli@1.1
    - uses: snok/install-poetry@v1.1.1
    - name: Install dependencies
      run: poetry install
    - name: Update data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: poetry run ./update.sh
